version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    groups:
      composer-prod-updates:
        update-types:
          - "minor"
          - "patch"
